---
title: "mod 3 hw"
output: html_document
date: '2022-09-26'
---
```{r}
library(tidyverse) 
library(Hmisc) # label()
library(lme4)
library(lmerTest)
```

```{r}
hsb <- hw_hsb
label(hsb$readach) = "Std. Reading Score"
label(hsb$sector) = "School Sector"

str(hsb$sector)
```

```{r}
hsb.clean <- hsb %>%
  mutate(.,
         sector.factor = as_factor(sector),
         female.factor = as_factor(female),
         minority.factor = as_factor(minority))

levels(hsb.clean$sector.factor) = c("Public", "Parochial")
levels(hsb.clean$female.factor) = c("Male", "Female")
levels(hsb.clean$minority.factor) = c("Non-Minority", "Minority")

str(hsb.clean$sector.factor)
```

```{r}
table(hsb.clean$sector.factor)
summary(hsb.clean)
```

```{r}
model1.null <- lmer(readach ~ (1|schoolid), REML = FALSE, data = hsb.clean)
summary(model1.null)
```

```{r}
null1.ICC <- 22.94/(22.94 + 61.06)
null1.ICC

```

```{r}
rand(model1.null)
```

```{r}
model2.null <- lmer(ses ~ (1|schoolid), REML = FALSE, data = hsb.clean)
summary(model2.null)
```

```{r}
null2.ICC <- 0.1597/(0.1597 + 0.4462)
null2.ICC

```

```{r}
rand(model2.null)
```